vich_uploader:
    db_driver: orm

    mappings:
        comments_avatar:
            uri_prefix: /images/avatarComment
            upload_destination: '%kernel.project_dir%/public/images/avatarComment'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true