framework:
    workflows:
        comment:
            type: state_machine
            audit_trail:
                enabled: 'true'
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Comment
            initial_marking: submitted
            place:
                - submitted
                - published
                - rejected
            transitions:
                publish:
                    from: submitted
                    to: published
                reject:
                    from: submitted
                    to: rejected
                moderate:
                    from: published
                    to: rejected